<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', 'BearJCC - Professional Portfolio')</title>
    <meta name="description" content="@yield('description', 'Professional portfolio showcasing web development projects and technical articles.')">

    <!-- Favicon -->
    <link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">
    <link rel="apple-touch-icon" href="{{ asset('apple-touch-icon.svg') }}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">

    <!-- Styles -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    
    <!-- Star Effects CSS -->
    <link rel="stylesheet" href="{{ asset('css/stars.css') }}">
    
    @stack('styles')
</head>
<body class="text-white font-['Oswald'] min-h-screen" style="background: url('{{ asset('images/brand/gradient-bg-professional.svg') }}') no-repeat center center fixed; background-size: cover;">
    <!-- Star Field Container -->
    <div id="stars" class="fixed inset-0 pointer-events-none z-0">
        <!-- Base star elements for JavaScript to clone -->
        <div id="circle" class="circle"></div>
        <div id="circle-animate" class="circle blink"></div>
        <!-- Stars will be generated by JavaScript -->
    </div>

    <!-- Main Content -->
    <div class="relative z-10">
        <!-- Header -->
        <header id="header" class="sticky top-0 z-50 bg-black/80 backdrop-blur-md border-b border-white/10 transition-all duration-300 shadow-lg">
            <nav class="max-w-7xl mx-auto px-6 py-3">
                <div class="flex items-center justify-between">
                    <!-- Logo - Hugs left side -->
                    <a href="{{ route('home') }}" class="flex items-center space-x-3 group">
                        <img id="logo" src="{{ asset('images/brand/bear-logo-32.svg') }}" alt="BearJCC Logo" class="w-8 h-8 transition-all duration-300 group-hover:scale-110 flex-shrink-0">
                        <span id="logo-text" class="text-xl font-bold tracking-wider transition-all duration-300 text-white leading-none">BearJCC</span>
                    </a>

                    <!-- Navigation Menu - Hugs right side -->
                    <div class="hidden md:flex items-center space-x-10">
                        <a href="{{ route('home') }}" class="text-gray-300 hover:text-white transition-colors font-medium text-sm py-2 px-3 relative after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-white after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:duration-300">Home</a>
                        <a href="{{ route('about') }}" class="text-gray-300 hover:text-white transition-colors font-medium text-sm py-2 px-3 relative after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-white after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:duration-300">About</a>
                        <a href="{{ route('projects.index') }}" class="text-gray-300 hover:text-white transition-colors font-medium text-sm py-2 px-3 relative after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-white after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:duration-300">Projects</a>
                        <a href="{{ route('articles.index') }}" class="text-gray-300 hover:text-white transition-colors font-medium text-sm py-2 px-3 relative after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-white after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:duration-300">Blog</a>
                        <a href="{{ route('contact.index') }}" class="text-gray-300 hover:text-white transition-colors font-medium text-sm py-2 px-3 relative after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-white after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:duration-300">Contact</a>
                        <a href="{{ route('components.showcase') }}" class="text-gray-300 hover:text-white transition-colors font-medium text-sm py-2 px-3 relative after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-white after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:duration-300">Components</a>
                    </div>

                    <!-- Mobile Menu Button -->
                    <button id="mobile-menu-button" class="md:hidden text-gray-300 hover:text-white p-2 rounded-md hover:bg-white/10 transition-colors">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
                        </svg>
                    </button>
                </div>

                <!-- Mobile Menu -->
                <div id="mobile-menu" class="md:hidden hidden mt-2 pb-2 border-t border-white/10">
                    <div class="flex flex-col space-y-1 pt-2">
                        <a href="{{ route('home') }}" class="text-gray-300 hover:text-white transition-colors py-2 px-3 rounded-md hover:bg-white/10 font-medium text-sm">Home</a>
                        <a href="{{ route('about') }}" class="text-gray-300 hover:text-white transition-colors py-2 px-3 rounded-md hover:bg-white/10 font-medium text-sm">About</a>
                        <a href="{{ route('projects.index') }}" class="text-gray-300 hover:text-white transition-colors py-2 px-3 rounded-md hover:bg-white/10 font-medium text-sm">Projects</a>
                        <a href="{{ route('articles.index') }}" class="text-gray-300 hover:text-white transition-colors py-2 px-3 rounded-md hover:bg-white/10 font-medium text-sm">Blog</a>
                        <a href="{{ route('contact.index') }}" class="text-gray-300 hover:text-white transition-colors py-2 px-3 rounded-md hover:bg-white/10 font-medium text-sm">Contact</a>
                        <a href="{{ route('components.showcase') }}" class="text-gray-300 hover:text-white transition-colors py-2 px-3 rounded-md hover:bg-white/10 font-medium text-sm">Components</a>
                    </div>
                </div>
            </nav>
        </header>

        <!-- Main Content -->
        <main class="w-full">
            @yield('content')
        </main>

        <!-- Footer -->
        <footer class="bg-black/20 border-t border-white/10 mt-24">
            <div class="max-w-7xl mx-auto px-6 py-8">
                <div class="flex flex-col md:flex-row justify-between items-center">
                    <div class="flex items-center space-x-2 mb-4 md:mb-0">
                        <img src="{{ asset('images/brand/bear-logo-16.svg') }}" alt="BearJCC Logo" class="w-5 h-5">
                        <span class="text-base font-bold">BearJCC</span>
                    </div>
                    <div class="text-white/60 text-sm">
                        © {{ date('Y') }} BearJCC. All rights reserved.
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <!-- Star Effects JavaScript -->
    <script src="{{ asset('js/stars.js') }}"></script>
    <script src="{{ asset('js/scroll.js') }}"></script>
    
    <!-- Initialize Star Field -->
    <script>
        // Initialize star field when page loads
        document.addEventListener('DOMContentLoaded', function() {
            if (typeof stars === 'function') {
                stars();
            }
        });
    </script>
    
    <!-- Mobile Menu Toggle -->
    <script>
        document.getElementById('mobile-menu-button').addEventListener('click', function() {
            const mobileMenu = document.getElementById('mobile-menu');
            mobileMenu.classList.toggle('hidden');
        });
    </script>

    <!-- Scroll-based navbar expansion -->
    <script>
        let lastScrollTop = 0;
        const header = document.getElementById('header');
        const logo = document.getElementById('logo');
        const logoText = document.getElementById('logo-text');

        window.addEventListener('scroll', function() {
            const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
            
            if (scrollTop > 100) {
                // Expanded state - more prominent
                header.classList.add('py-4');
                header.classList.remove('py-3');
                logo.classList.remove('w-8', 'h-8');
                logo.classList.add('w-10', 'h-10');
                logoText.classList.remove('text-xl');
                logoText.classList.add('text-2xl');
            } else {
                // Collapsed state - more compact
                header.classList.remove('py-4');
                header.classList.add('py-3');
                logo.classList.remove('w-10', 'h-10');
                logo.classList.add('w-8', 'h-8');
                logoText.classList.remove('text-2xl');
                logoText.classList.add('text-xl');
            }
            
            lastScrollTop = scrollTop;
        });
    </script>

    @stack('scripts')
</body>
</html>
