<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', 'BearJCC - Professional Portfolio')</title>
    <meta name="description" content="@yield('description', 'Professional portfolio showcasing web development projects and technical articles.')">

    <!-- Favicon -->
    <link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">
    <link rel="apple-touch-icon" href="{{ asset('apple-touch-icon.svg') }}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">

    <!-- Styles -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    
    <!-- Star Effects CSS -->
    <link rel="stylesheet" href="{{ asset('css/stars.css') }}">
    
    @stack('styles')
</head>
<body class="text-white font-['Oswald'] min-h-screen" style="background: url('{{ asset('images/brand/gradient-bg-professional.svg') }}') no-repeat center center fixed; background-size: cover;">
    <!-- Star Field Container -->
    <div id="stars" class="fixed inset-0 pointer-events-none z-0">
        <!-- Stars will be generated by JavaScript -->
    </div>

    <!-- Main Content -->
    <div class="relative z-10">
        <!-- Header -->
        <header class="sticky top-0 z-50 bg-black/20 backdrop-blur-sm border-b border-white/10">
            <nav class="container mx-auto px-4 py-4">
                <div class="flex items-center justify-between">
                    <!-- Logo -->
                    <a href="{{ route('home') }}" class="flex items-center space-x-3 group">
                        <img src="{{ asset('images/brand/bear-logo-32.svg') }}" alt="BearJCC Logo" class="w-8 h-8 transition-transform group-hover:scale-110">
                        <span class="text-xl font-bold tracking-wider">BearJCC</span>
                    </a>

                    <!-- Navigation Menu -->
                    <div class="hidden md:flex items-center space-x-8">
                        <a href="{{ route('home') }}" class="text-white/80 hover:text-white transition-colors">Home</a>
                        <a href="{{ route('about') }}" class="text-white/80 hover:text-white transition-colors">About</a>
                        <a href="{{ route('projects.index') }}" class="text-white/80 hover:text-white transition-colors">Projects</a>
                        <a href="{{ route('articles.index') }}" class="text-white/80 hover:text-white transition-colors">Blog</a>
                        <a href="{{ route('contact.index') }}" class="text-white/80 hover:text-white transition-colors">Contact</a>
                    </div>

                    <!-- Mobile Menu Button -->
                    <button id="mobile-menu-button" class="md:hidden text-white">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
                        </svg>
                    </button>
                </div>

                <!-- Mobile Menu -->
                <div id="mobile-menu" class="md:hidden hidden mt-4 pb-4 border-t border-white/10">
                    <div class="flex flex-col space-y-4 pt-4">
                        <a href="{{ route('home') }}" class="text-white/80 hover:text-white transition-colors">Home</a>
                        <a href="{{ route('about') }}" class="text-white/80 hover:text-white transition-colors">About</a>
                        <a href="{{ route('projects.index') }}" class="text-white/80 hover:text-white transition-colors">Projects</a>
                        <a href="{{ route('articles.index') }}" class="text-white/80 hover:text-white transition-colors">Blog</a>
                        <a href="{{ route('contact.index') }}" class="text-white/80 hover:text-white transition-colors">Contact</a>
                    </div>
                </div>
            </nav>
        </header>

        <!-- Main Content -->
        <main class="container mx-auto px-4 py-8">
            @yield('content')
        </main>

        <!-- Footer -->
        <footer class="bg-black/20 border-t border-white/10 mt-16">
            <div class="container mx-auto px-4 py-8">
                <div class="flex flex-col md:flex-row justify-between items-center">
                    <div class="flex items-center space-x-3 mb-4 md:mb-0">
                        <img src="{{ asset('images/brand/bear-logo-16.svg') }}" alt="BearJCC Logo" class="w-6 h-6">
                        <span class="text-lg font-bold">BearJCC</span>
                    </div>
                    <div class="text-white/60 text-sm">
                        © {{ date('Y') }} BearJCC. All rights reserved.
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <!-- Star Effects JavaScript -->
    <script src="{{ asset('js/stars.js') }}"></script>
    <script src="{{ asset('js/scroll.js') }}"></script>
    
    <!-- Mobile Menu Toggle -->
    <script>
        document.getElementById('mobile-menu-button').addEventListener('click', function() {
            const mobileMenu = document.getElementById('mobile-menu');
            mobileMenu.classList.toggle('hidden');
        });
    </script>

    @stack('scripts')
</body>
</html>
